version: "3.3"
# Este es un archivo de docker-compose.yml para configurar el uso de contenedores de software.

services:
  mysql-soderia:
    image: mysql:8.0
    container_name: mysql-soderia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: soderia
    ports:
      - "3308:3306"

  soderia:
    image: python:3.9.5
    container_name: soderia
    working_dir: /opt/back_end
    volumes:
      - .:/opt/back_end
    ports:
      - "8004:8000"
    depends_on:
      - mysql-soderia
    stdin_open: true
    tty: true