version: "3.3"
# Este es un archivo de docker-compose.yml para configurar el uso de contenedores de software.

services:
  prueba_django:
    # Imagen a utilizar:
    image: python:3.9.5
    # Nombre del container:
    container_name: soderia
    # Comportamiento ante fallos y al iniciar el sistema:
    restart: always
    # Carpetas enlazadas:
    volumes:
      # Source code directory:
      - type: bind
        source: .
        target: /opt/back_end
    # Puertos enlazados:
    ports:
      - "8004:8000"
    environment:
      DB_NAME: soderia
      DB_USER: root
      DB_PASSWORD: admin
      DB_HOST: host.docker.internal
      DB_PORT: "3306"
    # Control de consola:
    stdin_open: true
    tty: true
