# Generated by Django 3.2.2 on 2026-02-17 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id_datos_personales', models.AutoField(db_column='id_datos_personales', primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'datos_personales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'barrio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Camioneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En ruta'), ('FUERA', 'Fuera de servicio')], default='DISPONIBLE', max_length=20)),
                ('is_deposito', models.BooleanField(default=False)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camionetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'camioneta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tipo_cliente', models.CharField(choices=[('PERSONA', 'Persona'), ('COMERCIO', 'Comercio')], default='PERSONA', max_length=20)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT')], default='DNI', max_length=10)),
                ('numero_documento', models.CharField(max_length=30)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('referencias', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='Proyecto_Soderia.barrio')),
            ],
            options={
                'db_table': 'client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado'), ('EN_REPARTO', 'En reparto'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('PAGADO', 'Pagado')], default='CREADO', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forma_pago', models.CharField(blank=True, max_length=60)),
                ('pago_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pago_motivo', models.CharField(blank=True, max_length=200)),
                ('pago_fecha', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camioneta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='Proyecto_Soderia.camioneta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Proyecto_Soderia.client')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('capacidad_litros', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tipo_envase', models.CharField(choices=[('BOTELLA', 'Botella'), ('SIFON', 'Sifon'), ('BIDON', 'Bidon')], default='BOTELLA', max_length=20)),
                ('retornable', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_por_camioneta', models.IntegerField(blank=True, null=True)),
                ('unidad_venta', models.CharField(choices=[('UNIDAD', 'Unidad'), ('PACK', 'Pack'), ('CAJA', 'Caja')], default='UNIDAD', max_length=20)),
                ('requiere_envase', models.BooleanField(default=False)),
                ('deposito_envase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'zona',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='StockMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega'), ('DEVOLUCION', 'Devolucion'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camioneta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Proyecto_Soderia.camioneta')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='Proyecto_Soderia.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='Proyecto_Soderia.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stockmovimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado'), ('EN_REPARTO', 'En reparto'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('PAGADO', 'Pagado')], max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Proyecto_Soderia.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_estados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidoestado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Proyecto_Soderia.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='Proyecto_Soderia.producto')),
            ],
            options={
                'db_table': 'pedidodetalle',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='Proyecto_Soderia.zona'),
        ),
        migrations.AddField(
            model_name='camioneta',
            name='zonas',
            field=models.ManyToManyField(blank=True, db_table='camioneta_zonas', related_name='camionetas', to='Proyecto_Soderia.Zona'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barrios', to='Proyecto_Soderia.zona'),
        ),
        migrations.CreateModel(
            name='StockCamioneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('camioneta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='Proyecto_Soderia.camioneta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_camionetas', to='Proyecto_Soderia.producto')),
            ],
            options={
                'db_table': 'stockcamioneta',
                'ordering': ['producto__nombre'],
                'unique_together': {('camioneta', 'producto')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='barrio',
            unique_together={('nombre', 'zona')},
        ),
    ]
