# Generated by Django 3.2.2 on 2026-04-23 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Soderia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='Proyecto_Soderia.deposito'),
        ),
    ]
