# Generated by Django 3.2.2 on 2026-02-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Soderia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camioneta',
            name='is_deposito',
        ),
    ]
