# Generated by Django 3.2.2 on 2026-04-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Soderia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaweb',
            name='motivo',
            field=models.CharField(choices=[('CLIENTE', 'Quiero ser cliente'), ('PRECIOS', 'Consulta de precios'), ('GENERAL', 'Consulta general'), ('RECLAMO', 'Reclamo / Problema')], default='GENERAL', max_length=20),
        ),
    ]
