# Generated by Django 3.2.2 on 2026-02-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Soderia', '0002_remove_camioneta_is_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'deposito',
            },
        ),
        migrations.CreateModel(
            name='StockDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.IntegerField()),
                ('deposito', models.ForeignKey(db_column='deposito_id', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='Proyecto_Soderia.deposito')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='stocks_deposito', to='Proyecto_Soderia.producto')),
            ],
            options={
                'db_table': 'stockdeposito',
                'unique_together': {('deposito', 'producto')},
            },
        ),
    ]
