# Generated by Django 3.2.2 on 2026-04-23 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Soderia', '0002_pedido_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovimiento',
            name='camioneta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Proyecto_Soderia.camioneta'),
        ),
    ]
