# Generated by Django 3.2.2 on 2026-04-20 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Proyecto_Soderia', '0002_consultaweb_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='orden_entrega',
            field=models.PositiveIntegerField(blank=True, help_text='Orden de entrega asignado en despacho', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado'), ('DESPACHADO', 'Despachado'), ('EN_REPARTO', 'En reparto'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('PAGADO', 'Pagado')], default='CREADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoestado',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ASIGNADO', 'Asignado'), ('DESPACHADO', 'Despachado'), ('EN_REPARTO', 'En reparto'), ('ENTREGADO', 'Entregado'), ('DEVUELTO', 'Devuelto'), ('PAGADO', 'Pagado')], max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.IntegerField()),
                ('detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
