# Generated by Django 3.2.2 on 2026-02-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Soderia', '0003_deposito_stockdeposito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'managed': True},
        ),
    ]
