# Generated by Django 3.2.2 on 2026-04-23 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Soderia', '0003_alter_stockmovimiento_camioneta'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovimiento',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='Proyecto_Soderia.deposito'),
        ),
        migrations.AddField(
            model_name='stockmovimiento',
            name='deposito_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='Proyecto_Soderia.deposito'),
        ),
        migrations.AlterField(
            model_name='stockmovimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTREGA', 'Entrega'), ('DEVOLUCION', 'Devolucion'), ('AJUSTE', 'Ajuste'), ('VENTA', 'Venta'), ('TRANSFERENCIA', 'Transferencia'), ('CARGA', 'Carga')], max_length=20),
        ),
    ]
