# Generated by Django 3.2.2 on 2026-04-09 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Soderia', '0004_alter_datospersonales_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('LEIDA', 'Leída'), ('CONTACTADA', 'Contactada'), ('CONVERTIDA', 'Convertida a cliente'), ('DESCARTADA', 'Descartada')], default='NUEVA', max_length=20)),
                ('notas_internas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente_convertido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_origen', to='Proyecto_Soderia.client')),
            ],
            options={
                'verbose_name': 'Consulta web',
                'verbose_name_plural': 'Consultas web',
                'db_table': 'web_inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
