# Generated by Django 3.2.2 on 2026-04-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Soderia', '0004_auto_20260422_2140'),
        ('Proyecto_Soderia', '0006_remove_despacho_constraint'),
    ]

    operations = [
    ]
